version: "2"

services:
  voting-app:
    image: pottava/python:2.7
    command: python app.py
    volumes:
      - ./voting-app/packages:/usr/lib/python2.7/site-packages/
      - ./voting-app:/app
    working_dir: /app
    ports:
      - "5000:80"
    links:
      - redis
    environment:
      - OPTION_A
      - OPTION_B
    networks:
      - front-tier
      - back-tier

  result-app:
    image: pottava/nodejs
    command: node server.js
    volumes:
      - ./result-app:/app
    working_dir: /app
    ports:
      - "5001:4000"
    links:
      - db
    networks:
      - front-tier
      - back-tier

  worker:
    build: ./worker
    links:
      - db
      - redis
    networks:
      - back-tier

  redis:
    image: pottava/redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: kiasaki/alpine-postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  postgres-data:

networks:
  front-tier:
  back-tier:
